# Generated by Django 4.2.16 on 2025-02-14 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0018_auto_20230925_2243"),
        ("payroll", "0022_alter_csvreconciliationupload_user_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpaymentpoint",
            name="payment_method",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalpayroll",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="location.location",
            ),
        ),
        migrations.AddField(
            model_name="paymentpoint",
            name="payment_method",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payroll",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="location.location",
            ),
        ),
    ]
